### ISSUE TITLE
How can I avoid using host network mode and just bind a ports?

### ISSUE THREAD

**Issue by AbdullaM5** [schors/tgdante2#7]
```
version: '3.3'
services:
  ...
  socks5-proxy-v2:
    container_name: socks5-proxy-v2
    image: schors/tgdante2
    ports:
      - 1081:1080
    environment:
      - USER=user
      - PASS=pass
      - PORT=1080
    restart: unless-stopped
    #network_mode: "host"
```
